package com.cse3111project.bot.spring.category.academic.credit_transfer;

import com.cse3111project.bot.spring.model.engine.marker.SQLAccessible;
import com.cse3111project.bot.spring.model.engine.SQLDatabaseEngine;
import com.cse3111project.bot.spring.model.engine.marker.StaticAccessible;
import com.cse3111project.bot.spring.model.engine.StaticDatabaseEngine;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.net.URISyntaxException;

import java.util.Scanner;
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;
import com.cse3111project.bot.spring.utility.Utilities;

import com.cse3111project.bot.spring.exception.NotSQLAccessibleError;
import com.cse3111project.bot.spring.exception.NotStaticAccessibleError;
import com.cse3111project.bot.spring.exception.StaticDatabaseFileNotFoundException;

public class LocalInstitutionCreditTransfer extends CreditTransfer implements SQLAccessible, StaticAccessible {
    public static final String INSTITUTION_KEYWORD[] = { "Centennial College",
                                                         "Chu Hai College of Higher Education",
                                                         "City University of Hong Kong",
                                                         "College of International Education, Hong Kong Baptist University",
                                                         "Community College of City University",
                                                         "Hang Seng Management College",
                                                         "Hong Kong Community College, The Hong Kong Polytechnic University",
                                                         "Hong Kong Institute of Vocational Education",
                                                         "Hong Kong Shue Yan University",
                                                         "Lingnan University",
                                                         "School of Continuing Education, Hong Kong Baptist University",
                                                         "School of Continuing and Professional Studies, The Chinese University of Hong Kong",
                                                         "School of Professional and Continuing Education, The University of Hong Kong",
                                                         "The Chinese University of Hong Kong",
                                                         "The Hong Kong Institute of Education",
                                                         "The Hong Kong Polytechnic University",
                                                         "The Open University of Hong Kong",
                                                         "The University of Hong Kong",
                                                         "Yale-China Chinese Language Centre"
                                                        };

    public static final String SUBJECT_KEYWORD[] = { "(DCO10111 / AST10111) + (DCO10112 / AST21112)",
                                                     "(HP83-277 / HPHS4001) + (HP83-280 / HPHS4004) + (HP83-279 / HPHS4003) + (HP83-377 / HPHS4008)",
                                                     "166-PP2104-01",
                                                     "172-PP2105-01",
                                                     "ABA101A+ ABA101B",
                                                     "ABCT1102",
                                                     "ABCT1103",
                                                     "ABCT1103+ABCT1741+ABCT1742+ABCT2774",
                                                     "ABCT1700",
                                                     "ABCT1D04 / ABCT1101",
                                                     "ABCT226",
                                                     "ABCT242 / ABCT2742",
                                                     "ABCT247 / ABCT3747",
                                                     "ABCT2741",
                                                     "ABCT2775",
                                                     "ABCT359 / ABCT3759",
                                                     "AC1105",
                                                     "AC1115",
                                                     "ACC4001",
                                                     "ACCT 101 + ACCT 102",
                                                     "ACCT1101",
                                                     "AEC3845",
                                                     "AMA1006",
                                                     "AMA1007 + AMA2882",
                                                     "AMA1100",
                                                     "AMA1100 + AMA1102",
                                                     "AMA1103",
                                                     "AMA1104",
                                                     "AMA1110 + AMA1120",
                                                     "AMA2104",
                                                     "AMA2111",
                                                     "AP10006",
                                                     "AP10007",
                                                     "AP10008",
                                                     "AP10009",
                                                     "AP20002",
                                                     "AP20005",
                                                     "AP20008",
                                                     "APSS111/APSS1A07",
                                                     "APSS1A08",
                                                     "APSS2910 / APSS1B17",
                                                     "ASC1303+ ASC1310",
                                                     "ASC3441",
                                                     "ASC3442",
                                                     "ASC3443",
                                                     "ASC3876 + ASC3881",
                                                     "ASC3878",
                                                     "ASD3001",
                                                     "ASD3001+ASD3002",
                                                     "ASD3002 + ASD3006",
                                                     "ASD3003",
                                                     "ASD3005",
                                                     "ASD3005 + ITE4901",
                                                     "ASD3007",
                                                     "ASD3007+ SAS4205+ SAS4209",
                                                     "ASD3008",
                                                     "ASD3008+SAS4018",
                                                     "ASD4012",
                                                     "ASD4012+SAS4204",
                                                     "ASD4012+SAS4204+SAS4209",
                                                     "AST 21204",
                                                     "AST10201",
                                                     "AST10210 / DCO10210",
                                                     "AST10962",
                                                     "AST11103",
                                                     "AST11201",
                                                     "AST11202",
                                                     "AST20105",
                                                     "AST20210",
                                                     "AST20211",
                                                     "AST20302 / DCO20302",
                                                     "AST20307",
                                                     "AST20613",
                                                     "AST21020",
                                                     "AST21104",
                                                     "AST21104 / DCO21104",
                                                     "AST21111",
                                                     "AST21112",
                                                     "AST21115",
                                                     "AST21115+AST11117",
                                                     "AST21117",
                                                     "AST21203",
                                                     "AST21204",
                                                     "AST21205",
                                                     "AST21212 / DCO21212",
                                                     "AST21213",
                                                     "AST21401",
                                                     "AST21600",
                                                     "AST21962",
                                                     "AST22112",
                                                     "BAN4102",
                                                     "BAN4109",
                                                     "BCH1200",
                                                     "BM1208",
                                                     "BM1301",
                                                     "BM1410",
                                                     "BM1415",
                                                     "BPHM 1116",
                                                     "BSE4202 + BSE4403",
                                                     "BSE4301",
                                                     "BST 22317",
                                                     "BST11512",
                                                     "BST11513+ BST21551+ BST21552+ BST21553",
                                                     "BST11959",
                                                     "BST12331",
                                                     "BST12345",
                                                     "BST12359",
                                                     "BST12511",
                                                     "BST12512",
                                                     "BST12624 + BST12315 + BST22611",
                                                     "BST21531+ BST21532",
                                                     "BST22326 + BST22353 + BST12350",
                                                     "BST22326 + BST22353 + BST12350 + BST22325",
                                                     "BST22347",
                                                     "BST22531+ BST22532",
                                                     "BUAD1002",
                                                     "BUAD3005 ",
                                                     "BUAD3006",
                                                     "BUAD3008",
                                                     "BUS 112",
                                                     "BUS 20305",
                                                     "BUS100",
                                                     "BUS1001",
                                                     "BUS10112",
                                                     "BUS10160",
                                                     "BUS10188",
                                                     "BUS10250",
                                                     "BUS10306",
                                                     "BUS10311",
                                                     "BUS10407",
                                                     "BUS10408",
                                                     "BUS20112 + BUS20180",
                                                     "BUS20119",
                                                     "BUS20136 + BUS20180",
                                                     "BUS20165",
                                                     "BUS20251",
                                                     "BUS20269",
                                                     "BUS20302",
                                                     "BUS20322",
                                                     "BUS20323",
                                                     "BUS20324",
                                                     "BUS20326",
                                                     "BUS20372",
                                                     "BUS20402",
                                                     "BUS20404",
                                                     "BUS20486",
                                                     "BUS3001",
                                                     "BUS3003",
                                                     "BUS3004",
                                                     "BUS3008",
                                                     "BUS4001",
                                                     "BUS4005",
                                                     "BUSI1002",
                                                     "BUSI1007",
                                                     "CAES1000",
                                                     "CB2201",
                                                     "CB2300",
                                                     "CB2400",
                                                     "CBE2027+ CBE3027",
                                                     "CBS1100P",
                                                     "CC 66-213/CCAC4006 + CC66-214",
                                                     "CC 66-215/ CCAC4008 + CC66-216",
                                                     "CC 66-221/ CCAC4012A",
                                                     "CC 66-222 / CCAC4013",
                                                     "CC 66-388 / CCMK4002",
                                                     "CC 66-391 / CCMK4008",
                                                     "CC 66-460 / CCAC4019",
                                                     "CC-66-390 / CCMK4006",
                                                     "CC1C07",
                                                     "CC2004",
                                                     "CC2005 / CCN2041",
                                                     "CC2011/ CCN1019",
                                                     "CC2019 / CCN1017",
                                                     "CC2201",
                                                     "CC2202",
                                                     "CC2203",
                                                     "CC2204",
                                                     "CC2205",
                                                     "CC2305 / CCN2246",
                                                     "CC2404",
                                                     "CC2406 / CCN1045",
                                                     "CC2417 + CC2418",
                                                     "CC2425+ CC3476 / CCN2243 + CCN2244",
                                                     "CC2C08",
                                                     "CC2C10",
                                                     "CC2C10P",
                                                     "CC2C12P",
                                                     "CC2C13P",
                                                     "CC2F01P",
                                                     "CC3135",
                                                     "CC3143",
                                                     "CC3201",
                                                     "CC3203",
                                                     "CC3204",
                                                     "CC3206 / CCN3140",
                                                     "CC3208",
                                                     "CC3209",
                                                     "CC3210",
                                                     "CC3301",
                                                     "CC3302",
                                                     "CC3303",
                                                     "CC3304",
                                                     "CC3305",
                                                     "CC3308 / CCN3141",
                                                     "CC3311 / CCN2249",
                                                     "CC3313",
                                                     "CC3318 / CCN2275",
                                                     "CC3319 / CCN2274",
                                                     "CC3401",
                                                     "CC3403 / CCN2237",
                                                     "CC3409",
                                                     "CC3423 / CCN2266",
                                                     "CC3430",
                                                     "CC3456",
                                                     "CC3458 / CCN3139",
                                                     "CC3475 / CCN2276",
                                                     "CC3477 / CCN2277",
                                                     "CC3487",
                                                     "CC3728 CCN2261",
                                                     "CC3729",
                                                     "CC3731",
                                                     "CC3732 / CCN2269",
                                                     "CC3735 / CCN3138",
                                                     "CC3736",
                                                     "CC3745 / CCN2254",
                                                     "CC66-290 / CCIM4029",
                                                     "CC66-292 /CCIM4035",
                                                     "CC66-293 / CCIM4030",
                                                     "CC66-294 /CCIM4033",
                                                     "CC66-298 / CCIM4048",
                                                     "CC66-312 / CCIM4034",
                                                     "CC66-314 / CCIM4053",
                                                     "CC66-314 /CCIM4053",
                                                     "CC66-315 / CCIM4057",
                                                     "CC66-317 / CCIM4031",
                                                     "CC66-318 / CCIM4036",
                                                     "CC66-323 /CCIM4047",
                                                     "CC66-324 + CC66-310 / CCIM4050 + CCIM4051",
                                                     "CC66-324 /CCIM4050",
                                                     "CC66-816 / CCMK5005",
                                                     "CC88-125 / CC88-649 / CCAH3004 / CCAH4001",
                                                     "CC88-157",
                                                     "CC88-157 + CC88-786 / CCST3002 + CCST4101",
                                                     "CC88-157 /CCST3002",
                                                     "CC88-166 / CCMA3001",
                                                     "CC88-167 / CCST4009",
                                                     "CC88-233 / CCST 4011",
                                                     "CC88-246 / CD85-215-78 / CCIT4009",
                                                     "CC88-249 / CCST4012",
                                                     "CC88-250 / CCST4013",
                                                     "CC88-257 / CCPH4002",
                                                     "CC88-259 / CCSS4004",
                                                     "CC88-265 / CCST4017",
                                                     "CC88-265/CCST4017 + CC88-167/CCST4009 + CC88-667/CCST4084",
                                                     "CC88-266 / CCST4018",
                                                     "CC88-277 / CCBS4009",
                                                     "CC88-281 / CCCU4006",
                                                     "CC88-283 / CCMA4005",
                                                     "CC88-285 / CCPH4003",
                                                     "CC88-298 /CCIT4013",
                                                     "CC88-299 / CCIT4014",
                                                     "CC88-314 /CCIT4015",
                                                     "CC88-319 / CCIT4018",
                                                     "CC88-321 / CCIT4020",
                                                     "CC88-322 / CCIT 4021",
                                                     "CC88-322 / CCIT4021",
                                                     "CC88-324 / CCIT4023",
                                                     "CC88-340 / CCBS4007",
                                                     "CC88-341 / CCBS4005",
                                                     "CC88-342 / CCBS4008",
                                                     "CC88-349 / CCIT4024",
                                                     "CC88-422/CCST4025 + CC88-461/CCST4048",
                                                     "CC88-423 / CCST4026",
                                                     "CC88-447 / CCIT4026",
                                                     "CC88-452 / CCMA4008",
                                                     "CC88-456 /CCIT4029",
                                                     "CC88-468 /CCIT4030",
                                                     "CC88-580 /CCST4069",
                                                     "CC88-581 /CCST4070",
                                                     "CC88-593",
                                                     "CC88-620 /CCIT4033",
                                                     "CC88-621 +CC88-297",
                                                     "CC88-622 /CCIT4035",
                                                     "CC88-624 / CCIT4037",
                                                     "CC88-627 / CCIT4040",
                                                     "CC88-636 / CCIT4048",
                                                     "CC88-637 / CCIT4049",
                                                     "CC88-638 / CCIT4004",
                                                     "CC88-642 / CCIT4051",
                                                     "CC88-645 /CCIT4052",
                                                     "CC88-646 / CCIT4053",
                                                     "CC88-663 /CCST4081",
                                                     "CC88-664 + CC88-422 + CC88-663 / CCST4082 + CCST4025 + CCST4081",
                                                     "CC88-665 + CC88-421 + CC88-423 / CCST4083 + CCST4024 + CCST4026",
                                                     "CC88-665 + CC88-421 /CCST4083 + CCST4024",
                                                     "CC88-667 / CCST4084",
                                                     "CC88-667/CCST4084 + CC88-265/CCST4017 + CC88-663/CCST4081",
                                                     "CC88-670 / CCIT4054",
                                                     "CC88-671 /CCIT4055",
                                                     "CC88-744 / CCST4091",
                                                     "CC88-746 / CCST4093",
                                                     "CC88-759 / CCIT4057",
                                                     "CC88-760 / CCIT4058",
                                                     "CC88-761 /CCIT4059",
                                                     "CC88-764 / CCMA4009",
                                                     "CC88-769 /CCIT4060",
                                                     "CC88-773 /CCIT4063",
                                                     "CC88-774 / CCIT4064",
                                                     "CC88-784 / CCST4099",
                                                     "CC88-820 / CCBS5001 + CC88-825",
                                                     "CC88-822 / CCBS5003",
                                                     "CC88-823 / CCBS5004 / CCBS4018",
                                                     "CC88-824 / CCBS5005",
                                                     "CCAC4012A + CCAC4012B",
                                                     "CCAH4003",
                                                     "CCAH4004",
                                                     "CCAH4009",
                                                     "CCBS 4001",
                                                     "CCBS4006",
                                                     "CCBS4010",
                                                     "CCBS4018",
                                                     "CCBS5008",
                                                     "CCC8001",
                                                     "CCC8002",
                                                     "CCCH 9024",
                                                     "CCCU4005",
                                                     "CCCU4015",
                                                     "CCGL 9040",
                                                     "CCIM4027",
                                                     "CCIM4037",
                                                     "CCIM4040 /CC66-321",
                                                     "CCIM4054",
                                                     "CCIM4069 /CC66-478 + CCIM4072 / CC66-481",
                                                     "CCIM4071",
                                                     "CCIM4073/CC66-482 + CCIM4076/CC66-534 + CCIM4077/CC66-535 + CCIM4075/CC66-533",
                                                     "CCIM4111 + CCIM41112",
                                                     "CCIT3002",
                                                     "CCIT4016",
                                                     "CCIT4019",
                                                     "CCIT4022",
                                                     "CCIT4031",
                                                     "CCIT4033 / CC88-620",
                                                     "CCIT4061",
                                                     "CCIT4073",
                                                     "CCMA4003",
                                                     "CCMA4008",
                                                     "CCMA4009",
                                                     "CCMK4010",
                                                     "CCMK5007",
                                                     "CCN1004 / CC2002",
                                                     "CCN1012",
                                                     "CCN1015",
                                                     "CCN1016",
                                                     "CCN1018",
                                                     "CCN1021",
                                                     "CCN1025",
                                                     "CCN1041",
                                                     "CCN1042",
                                                     "CCN1045 + CCN2250",
                                                     "CCN1048 + CCN2250 + CCN2269",
                                                     "CCN1049",
                                                     "CCN1050",
                                                     "CCN1051",
                                                     "CCN1101",
                                                     "CCN1106 + CCN1109",
                                                     "CCN1109",
                                                     "CCN1110",
                                                     "CCN1111",
                                                     "CCN2002",
                                                     "CCN2003",
                                                     "CCN2004",
                                                     "CCN2005",
                                                     "CCN2006",
                                                     "CCN2008",
                                                     "CCN2014",
                                                     "CCN2015",
                                                     "CCN2017",
                                                     "CCN2021",
                                                     "CCN2023",
                                                     "CCN2024",
                                                     "CCN2026",
                                                     "CCN2029",
                                                     "CCN2030",
                                                     "CCN2031",
                                                     "CCN2033",
                                                     "CCN2035",
                                                     "CCN2042",
                                                     "CCN2046",
                                                     "CCN2048",
                                                     "CCN2049",
                                                     "CCN2101",
                                                     "CCN2105",
                                                     "CCN2107",
                                                     "CCN2109",
                                                     "CCN2111",
                                                     "CCN2113",
                                                     "CCN2114",
                                                     "CCN2117",
                                                     "CCN2127",
                                                     "CCN2129",
                                                     "CCN2133",
                                                     "CCN2134",
                                                     "CCN2135",
                                                     "CCN2160",
                                                     "CCN2231",
                                                     "CCN2232 / CC3434",
                                                     "CCN2233 + CCN2234",
                                                     "CCN2236",
                                                     "CCN2238",
                                                     "CCN2239",
                                                     "CCN2240",
                                                     "CCN2241",
                                                     "CCN2242",
                                                     "CCN2248 + CCN2269",
                                                     "CCN2248 + CCN3128",
                                                     "CCN2248 + CCN3144",
                                                     "CCN2249",
                                                     "CCN2251",
                                                     "CCN2252",
                                                     "CCN2263",
                                                     "CCN2264",
                                                     "CCN2265",
                                                     "CCN2270",
                                                     "CCN2271",
                                                     "CCN2272",
                                                     "CCN2279",
                                                     "CCN2283",
                                                     "CCN2286+CCN2287",
                                                     "CCN3125 + CCN3144",
                                                     "CCN3129",
                                                     "CCN3133",
                                                     "CCN3134",
                                                     "CCN3135",
                                                     "CCN3136",
                                                     "CCN3142",
                                                     "CCPH4004",
                                                     "CCSS4006",
                                                     "CCSS4007",
                                                     "CCSS4009",
                                                     "CCSS4033",
                                                     "CCST 4081 + CCST4025 + CCST4017",
                                                     "CCST3005",
                                                     "CCST3006",
                                                     "CCST4012+CCST4029",
                                                     "CCST4012+CCST4111",
                                                     "CCST4015+CCST4097+CCST4098",
                                                     "CCST4023",
                                                     "CCST4030",
                                                     "CCST4036 + CCST4040",
                                                     "CCST4047",
                                                     "CCST4060",
                                                     "CCST4064 + CCMA4001",
                                                     "CCST4083 + (CCST4048 / CC88-461) + CCST4026",
                                                     "CCST4084+CCST4017+ CCST4048",
                                                     "CCST4085",
                                                     "CCST4086",
                                                     "CCST4095 + CCST4065",
                                                     "CCST4097 + CCST4098",
                                                     "CCTP4007",
                                                     "CCTP4008 + CCTP4009 + CCTP4010 / CC66-379 + CC66-380 + CC66-381",
                                                     "CCTP4011",
                                                     "CCTP4011 + CCTP4006 / CC66-369 + CC66-377",
                                                     "CCTP4013",
                                                     "CD85-215-15 / CCIT4068",
                                                     "CD85-215-22 / CCIT4067",
                                                     "CD85-215-59 / CCIT4011",
                                                     "CD85-215-80 / CCIT4025",
                                                     "CD85-233-14",
                                                     "CD85-233-21",
                                                     "CD85-233-21+ CD85-233-26",
                                                     "CD85-233-23 / CCIM4031",
                                                     "CD85-233-26",
                                                     "CEH1302+ CEH1308+ CEH1305",
                                                     "CEH1302+ CEH3514+ CEH3527",
                                                     "CEH3361",
                                                     "CEH3362",
                                                     "CEH3401",
                                                     "CEH3407",
                                                     "CEH3513",
                                                     "CEH3523",
                                                     "CGE 13208 / CGE 23208",
                                                     "CGE12301",
                                                     "CGE12303",
                                                     "CGE13101",
                                                     "CGE13201",
                                                     "CGE13203",
                                                     "CGE13204",
                                                     "CGE13206/ CEG23206",
                                                     "CGE14401",
                                                     "CGE14402 / DSS10103",
                                                     "CGE17105",
                                                     "CGE17301",
                                                     "CGE22402",
                                                     "CGE24401",
                                                     "CGE25401",
                                                     "CGE26503",
                                                     "CGE26504",
                                                     "CH1130",
                                                     "CHEM1070",
                                                     "CHI101 + CHI102 + CHI131 + CHI132",
                                                     "CHI4001",
                                                     "CHIN1001",
                                                     "CHN1002",
                                                     "CLA9012",
                                                     "CLA9015",
                                                     "CLC9012",
                                                     "CLD9006/GED122/CDS122",
                                                     "CM10331",
                                                     "CMA4003",
                                                     "COC1014",
                                                     "COMP250",
                                                     "CON3303 + CON4305",
                                                     "CON3402",
                                                     "CON3406",
                                                     "CON4331 + CON4333",
                                                     "CON4351 + CON4433 + CON4381 + CON2391",
                                                     "CON4351+ CON4433",
                                                     "CON4371",
                                                     "CON4403+CON4411+CON4412+CON4413+CON4433",
                                                     "CON4403+CON4433",
                                                     "CON4411",
                                                     "CON4414",
                                                     "CON4414+ CON4472",
                                                     "CON4432",
                                                     "CON4451",
                                                     "CS1102",
                                                     "CS1210",
                                                     "CS1225",
                                                     "CS1230",
                                                     "CSE10252",
                                                     "CSE10254",
                                                     "CSE19100",
                                                     "CSE19251",
                                                     "CTL2956",
                                                     "CUS329C",
                                                     "DCO10102",
                                                     "DCO10103",
                                                     "DCO10105 / DCO21105 / AST21105",
                                                     "DCO10106 / AST10106",
                                                     "DCO10111 / AST10111",
                                                     "DCO10113",
                                                     "DCO10113 / AST10113",
                                                     "DCO10114 / AST21114",
                                                     "DCO10210",
                                                     "DCO10211 /AST10211",
                                                     "DCO10301",
                                                     "DCO10303 / AST10303",
                                                     "DCO11202 /AST11202",
                                                     "DCO20112 / AST20112",
                                                     "DCO20112 /AST20112 + DCO10401 / AST10401",
                                                     "DCO20112+ DCO20113",
                                                     "DCO20113 / DCO10401 / AST10401",
                                                     "DCO20114 / AST20114",
                                                     "DCO20115 / AST20115",
                                                     "DCO20116",
                                                     "DCO20117",
                                                     "DCO20201 / AST20201",
                                                     "DCO20202",
                                                     "DCO20203 / AST20203",
                                                     "DCO20207 / AST20207",
                                                     "DCO20303+ DCO20304",
                                                     "DCO20306 / AST20306",
                                                     "DCO20401 / AST20401",
                                                     "DCO20403",
                                                     "DCO20404 / AST20404",
                                                     "DCO21160 / AST21160 + AST21616",
                                                     "DCO21211 / AST21211",
                                                     "DCO22113 / AST22113",
                                                     "DSS10621",
                                                     "DSS10643",
                                                     "DSS11104",
                                                     "DSS20325",
                                                     "DSS20401",
                                                     "DSS22302",
                                                     "E&I3410 +E&I4414",
                                                     "E&I3604",
                                                     "E&I3612+ E&I4611",
                                                     "E&I3613",
                                                     "E&I3664+ E&I4664",
                                                     "ECO1001",
                                                     "ECO1002",
                                                     "ECON 101",
                                                     "ECON1001 / 1210",
                                                     "ECON1002/ ECON1220",
                                                     "ECON103",
                                                     "EIE2101",
                                                     "EIE2261",
                                                     "EIE2264",
                                                     "EIE2302",
                                                     "EIE251",
                                                     "EIE264 / EIE2264",
                                                     "EIE282 / EIE2282",
                                                     "EIE3114",
                                                     "EIE3361",
                                                     "EIE3373",
                                                     "EIE3401S+EIE4402S",
                                                     "EIE3402S",
                                                     "EIE361 / EIE3361",
                                                     "EIE362 / EIE3362",
                                                     "EIE373 / EIE3373",
                                                     "EIE375 / EIE3375",
                                                     "EIE380",
                                                     "EIE399 / EIE3399",
                                                     "EIE4101",
                                                     "EIE4202",
                                                     "EIE4205 + EIE4210",
                                                     "EIE4206",
                                                     "EIE4400S",
                                                     "ELC2012",
                                                     "ELE3011",
                                                     "ELSS3007",
                                                     "ELSS3010",
                                                     "ELTU1002",
                                                     "EMT1300",
                                                     "ENCS1105",
                                                     "ENCS1106",
                                                     "ENCS1107",
                                                     "ENG1373/ENG3388",
                                                     "ENG2001",
                                                     "ENG2002",
                                                     "ENG2003",
                                                     "ENG236",
                                                     "ENG3102 + ENG3103 + MEC4101",
                                                     "ENG3102 + ENG3103 +ENG3109",
                                                     "ENG3102 + MEC4101 + MEC4109",
                                                     "ENG3104 + ENG3105 + EIE4106",
                                                     "ENG3104M + ENG3105 +EIE4106",
                                                     "ENG3105",
                                                     "ENG3107 + ENG3110",
                                                     "ENG3108 + MEC4104 + MEC4110",
                                                     "ENG3108 + MEC4701",
                                                     "ENG3109 + MEC3055",
                                                     "ENG3200 + CON4303 + CON4304",
                                                     "ENG3200 + CON4305",
                                                     "ENG3200 + ENG4200",
                                                     "ENG3200 + ENG4202",
                                                     "ENG3200 + MEC4103",
                                                     "ENG3200 + MEC4706",
                                                     "ENG3401S + ENG4401S",
                                                     "ENG3455",
                                                     "ENG3732",
                                                     "ENG3734",
                                                     "ENG3738",
                                                     "ENG4200+MEC3125+MEC4103",
                                                     "ENGG1000",
                                                     "ENS3401",
                                                     "FINA-3020",
                                                     "FINA0301",
                                                     "FINA1003",
                                                     "FINA2331",
                                                     "FINA2802",
                                                     "FREN1000",
                                                     "FREN2000",
                                                     "FREN3050",
                                                     "FSEH1203",
                                                     "FSEH1204",
                                                     "FSEH1206",
                                                     "GBS4116",
                                                     "GE1105",
                                                     "GE1114",
                                                     "GE1125",
                                                     "GE1501",
                                                     "GE2203",
                                                     "GE2227",
                                                     "GE2303",
                                                     "GE2305",
                                                     "GE2306",
                                                     "GE2314",
                                                     "GEAS 2112",
                                                     "GEAS2103",
                                                     "GEBS3003",
                                                     "GEC1A03",
                                                     "GEC1C25",
                                                     "GEC1H16C",
                                                     "GEC335",
                                                     "GECR1001",
                                                     "GECR1302",
                                                     "GECR4001",
                                                     "GECR5001 / GECR5001C",
                                                     "GECR5002",
                                                     "GECR5201",
                                                     "GECR5202",
                                                     "GECV4002",
                                                     "GECW1010",
                                                     "GEG1001/ GEA1003",
                                                     "GEH1014",
                                                     "GEN1001",
                                                     "GEN1011",
                                                     "GESC1102",
                                                     "GESC1109 / GESS1109",
                                                     "GESC1202",
                                                     "GESC1208",
                                                     "GESC1208 / GESS1208",
                                                     "GESS5101 / GESS5101C",
                                                     "GESS5301",
                                                     "HDGS0305C",
                                                     "HDMT1302",
                                                     "HDMT1303",
                                                     "HDMT1305",
                                                     "HDMT1306",
                                                     "HDMT1307",
                                                     "HDMT1308",
                                                     "HDMT1309",
                                                     "HP 83-217 / HPAC4001",
                                                     "HP 83-576 / HPAC4004",
                                                     "HP 83-577 / HPMS4001",
                                                     "HP 83-578 / HPMS4002",
                                                     "HP 83-579 / HPAC4005",
                                                     "HP 83-580 / HPMS4003",
                                                     "HP 83-581 / HPMS4004",
                                                     "HP 83-686 / HPMS4006",
                                                     "HP 83-687 / HPMS4007",
                                                     "HP 83-688 / HPMS4008",
                                                     "HP 83-689 / HPMS4009",
                                                     "HP 83-690 / HPMS4010",
                                                     "HP 83-691 / HPMS4011",
                                                     "HP 83-896 / HPMS4012",
                                                     "HP 83-992 / HPAC 4002",
                                                     "HP83-231",
                                                     "HP83-278 / HPHS4002+ HP83-283 /HPHS4007 + CC88-157 / CCST3002",
                                                     "HP83-590",
                                                     "HP83-897",
                                                     "HPAC4007",
                                                     "HPAC4008",
                                                     "HPCS4004",
                                                     "HPHR4004",
                                                     "HPMS4005",
                                                     "HPTH4003",
                                                     "HPTH4004",
                                                     "HPTH4025",
                                                     "HPTH4026",
                                                     "HST1194",
                                                     "HTM1005",
                                                     "HTM1A01",
                                                     "HTM1B05",
                                                     "HTM2310",
                                                     "HUM4001",
                                                     "HUM4002",
                                                     "IC2122",
                                                     "IIT1082",
                                                     "ISE246",
                                                     "ISE369",
                                                     "ITE3001",
                                                     "ITE3002",
                                                     "ITE3004",
                                                     "ITE3101",
                                                     "ITE3102",
                                                     "ITP3301",
                                                     "ITP4302",
                                                     "ITP4303",
                                                     "ITP4304 / ITP4314",
                                                     "ITP4305",
                                                     "ITP4306",
                                                     "ITP4307/ITP4317",
                                                     "ITP4308",
                                                     "ITP4309",
                                                     "ITP4312",
                                                     "ITP4313",
                                                     "ITP4315",
                                                     "ITP4318",
                                                     "ITP4903",
                                                     "ITP4905",
                                                     "ITP4906",
                                                     "ITP4907",
                                                     "ITP4912",
                                                     "LAN3003 + LAN4002",
                                                     "LAW110",
                                                     "LCC1010",
                                                     "LCE1010 + LCE1020 -",
                                                     "LFSC 1401",
                                                     "LFSC 1402",
                                                     "LFSC 1403",
                                                     "LFSC 1404",
                                                     "LGT2510",
                                                     "LGT2516 + LGT3505",
                                                     "LGT3501",
                                                     "LGT3505",
                                                     "LGT3508",
                                                     "LGT3524",
                                                     "LM1025",
                                                     "LM1035",
                                                     "LM1105",
                                                     "LM2105",
                                                     "LS1100",
                                                     "LS2040",
                                                     "LS2110",
                                                     "LS2120",
                                                     "LSGI1B02",
                                                     "MA0101",
                                                     "MATH1010",
                                                     "MATH2101",
                                                     "MEC3055",
                                                     "MEC3121",
                                                     "MEC3121 + MEC3122 + MEC4109 + MEC4107 + MEC4122",
                                                     "MEC3122 + MEC4109 + MEC4107 + MEC4122",
                                                     "MEC3122 + MEC4122 + MEC4109 + MEC4163",
                                                     "MEC3122 + MEC4122 + MEC4109 + MEC4163+MEC3123",
                                                     "MEC3123",
                                                     "MEC3123 + MEC3122 + MEC4109 + MEC4107 + MEC4122",
                                                     "MEC3125 + ENG4200",
                                                     "MEC3125 + MEC4103",
                                                     "MEC3400",
                                                     "MEC3400 + ITE4901",
                                                     "MEC3400 + MEC4407",
                                                     "MEC3400+MEC4406",
                                                     "MEC4101",
                                                     "MEC4102",
                                                     "MEC4111",
                                                     "MEC4121",
                                                     "MEC4121+MEC4110",
                                                     "MEC4163 + MEC4122",
                                                     "MEC4400",
                                                     "MEC4400+MEC4403",
                                                     "MEC4401 + MEC4402",
                                                     "MEC4406 + MEC4411",
                                                     "MEC4407",
                                                     "MET3401+ MET3405+ MET3409",
                                                     "MET3407",
                                                     "MGT4207",
                                                     "MK1003",
                                                     "MRTG3004",
                                                     "MRTG3103",
                                                     "NUFM 1501",
                                                     "NUFM1501",
                                                     "NUFM1504 + NUFM1505",
                                                     "PHI3105",
                                                     "PHI375",
                                                     "PHI399S",
                                                     "PHYS1111",
                                                     "PHYS1122",
                                                     "PHYS1712",
                                                     "POL4001",
                                                     "QA1110",
                                                     "SAS 3411+ SAS 3402",
                                                     "SAS 4211",
                                                     "SAS 4442+ SAS 4458",
                                                     "SAS3013",
                                                     "SAS3014",
                                                     "SAS3015",
                                                     "SAS3404",
                                                     "SAS4101",
                                                     "SAS4106 + SAS4107",
                                                     "SAS4108",
                                                     "SAS4203+ASD4017",
                                                     "SAS4204+SAS4205+SAS4202+SAS4203+SAS4206",
                                                     "SAS4205",
                                                     "SAS4206",
                                                     "SAS4206+SAS4203",
                                                     "SAS4210+SAS4203",
                                                     "SAS4305",
                                                     "SAS4306",
                                                     "SAS4307",
                                                     "SAS4310",
                                                     "SAS4311",
                                                     "SAS4416",
                                                     "SAS4435",
                                                     "SAS4442+ SAS4459",
                                                     "SAYT1114",
                                                     "SAYT1134",
                                                     "SCI2074",
                                                     "SCI2076",
                                                     "SCI4001",
                                                     "SEEM3450",
                                                     "SOC150",
                                                     "SOC3001",
                                                     "STAT1603",
                                                     "TC S350F",
                                                     "TC S351F",
                                                     "TC S356 F",
                                                     "TLS3003",
                                                     "TRA3211",
                                                     "TRA4306",
                                                     "UGEA2160",
                                                     "UGEB-1307",
                                                     "VIS2104",
                                                     "VIS399T (/VIS3399T)",
                                                     "VIS399V"
                                                   };

    // id institution course_code transfer_course_code restriction db_reference_no
    private static final String SQL_TABLE = "local_institutions_credits";
    private static final String STATIC_TABLE = "/static/academic/credit_transfer/localInstitutionCredits.txt";

    private List<String> localInstitutionQuery;
    private List<CreditTransferInfo> results;

    LocalInstitutionCreditTransfer(final List<String> localInstitutionQuery) {
        super();
        this.localInstitutionQuery = localInstitutionQuery;
    }

    @Override
    public synchronized String getDataFromSQL() throws NotSQLAccessibleError, URISyntaxException, SQLException {
        try (SQLDatabaseEngine database = new SQLDatabaseEngine(this.getClass(), SQL_TABLE)) {
            results = Collections.synchronizedList(new ArrayList<>());

            StringBuilder SQLStatement = new StringBuilder("SELECT institution, course_code, transfer_course_code, restriction FROM ")
                                             .append(SQL_TABLE)
                                             .append(" WHERE course_code = ?");
            for (int i = 1; i < localInstitutionQuery.size(); i++)
                SQLStatement.append(" OR course_code = ?");

            PreparedStatement SQLQuery = database.prepare(SQLStatement.toString());
            for (int i = 0; i < localInstitutionQuery.size(); i++)
                SQLQuery.setString(i + 1, localInstitutionQuery.get(i));

            ResultSet reader = database.executeQuery();
            while (reader.next()){
                results.add(new InstitutionCreditTransferInfo(null, 
                                                              reader.getString(1), reader.getString(2), 
                                                              reader.getString(3), reader.getString(4)));
            }

            return super.replyResults(results);
        }
    }

    @Override
    public synchronized String getDataFromStatic() throws NotStaticAccessibleError, StaticDatabaseFileNotFoundException {
        try (StaticDatabaseEngine database = new StaticDatabaseEngine(this.getClass(), STATIC_TABLE)) {
            results = Collections.synchronizedList(new ArrayList<>());

            Scanner reader = database.executeQuery();
            while (reader.hasNextLine()){
                String line = reader.nextLine();
                // starting with # is considered as comment
                if (line.startsWith("#") || line.length() == 0)
                    continue;

                List<String> row = reconstruct(line);
                if (localInstitutionQuery.contains(row.get(2)))
                    results.add(new InstitutionCreditTransferInfo(null, 
                                                                  row.get(1), row.get(2),
                                                                  row.get(3), row.get(4)));
            }

            return super.replyResults(results);
        }
    }
}
